version: "2.1"

services:
  nats:
    image: nats:1.4.1-linux
    expose:
      - "4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    hostname: nats
    restart: always
    volumes:
      - ./server-certs:/home/app/certs
    command: --tlsverify --tlscert=/home/app/certs/server-cert.pem --tlskey=/home/app/certs/server-key.pem --tlscacert=/home/app/certs/ca-cert.pem

  api:
    build:
      context: "."
    depends_on:
      - nats
    links:
      - nats
    hostname: api
    ports:
      - "8080:8080"
    restart: always
    environment:
      NATS_URL: nats://nats:4222
      # NATS_USER: ruser
      # NATS_PW: T0pS3cr3t
      API_PORT: 8789
      API_HOST: 0.0.0.0